#####GetLogisticOperators
GET http://localhost:8080/embalagensinteligentes/api/logisticoperators
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJkYW5pY2FyaWFzIiwiaWF0IjoxNzA1NjIxNzk1LCJleHAiOjE3MDU2NTA1OTV9.54NXIEt5e9_BWfkLNgRYFM_Lxzbatw2uETjgWD7U5rjTs78Er5s96-t34p_Md82b

#####GetSensorsByPackage -> Adicionar na pasta dos Packages do bruno
GET http://localhost:8080/embalagensinteligentes/api/packages/2/sensors
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJkYW5pY2FyaWFzIiwiaWF0IjoxNzA1NjIxNzk1LCJleHAiOjE3MDU2NTA1OTV9.54NXIEt5e9_BWfkLNgRYFM_Lxzbatw2uETjgWD7U5rjTs78Er5s96-t34p_Md82b

#####GetLogisticOperator
GET http://localhost:8080/embalagensinteligentes/api/logisticoperators/logistic_operator 1
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJkYW5pY2FyaWFzIiwiaWF0IjoxNzA1NjIxNzk1LCJleHAiOjE3MDU2NTA1OTV9.54NXIEt5e9_BWfkLNgRYFM_Lxzbatw2uETjgWD7U5rjTs78Er5s96-t34p_Md82b

#####CreateLogisticOperator
POST http://localhost:8080/embalagensinteligentes/api/logisticoperators
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJkYW5pY2FyaWFzIiwiaWF0IjoxNzA1NjIxNzk1LCJleHAiOjE3MDU2NTA1OTV9.54NXIEt5e9_BWfkLNgRYFM_Lxzbatw2uETjgWD7U5rjTs78Er5s96-t34p_Md82b

{
  "username": "novo_LogisticOperator",
  "name": "Novo LogisticOperator",
  "password": "pass123",
  "address": "Rua BBR",
  "phoneNumber": 123456789
}

#####EditLogisticOperator
PUT http://localhost:8080/embalagensinteligentes/api/logisticoperators/novo_LogisticOperator
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJkYW5pY2FyaWFzIiwiaWF0IjoxNzA1NjIxNzk1LCJleHAiOjE3MDU2NTA1OTV9.54NXIEt5e9_BWfkLNgRYFM_Lxzbatw2uETjgWD7U5rjTs78Er5s96-t34p_Md82b

{
  "name": "LogisticOperator Senior",
  "address": "Rua BBR  NOVO",
  "phoneNumber": 123456789
}

#####DeleteLogisticOperator
DELETE http://localhost:8080/embalagensinteligentes/api/logisticoperators/novo_LogisticOperator
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJkYW5pY2FyaWFzIiwiaWF0IjoxNzA1NjIxNzk1LCJleHAiOjE3MDU2NTA1OTV9.54NXIEt5e9_BWfkLNgRYFM_Lxzbatw2uETjgWD7U5rjTs78Er5s96-t34p_Md82b
