//--------------------PRODUCTS

##### AllProducts
GET http://localhost:8080/embalagensinteligentes/api/products
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJkYW5pY2FyaWFzIiwiaWF0IjoxNzA1NjIxNzk1LCJleHAiOjE3MDU2NTA1OTV9.54NXIEt5e9_BWfkLNgRYFM_Lxzbatw2uETjgWD7U5rjTs78Er5s96-t34p_Md82b

##### GetProduct
GET http://localhost:8080/embalagensinteligentes/api/products/3
Accept: application/json

##### CreateProduct
POST http://localhost:8080/embalagensinteligentes/api/products
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJkYW5pY2FyaWFzIiwiaWF0IjoxNzA1NjIxNzk1LCJleHAiOjE3MDU2NTA1OTV9.54NXIEt5e9_BWfkLNgRYFM_Lxzbatw2uETjgWD7U5rjTs78Er5s96-t34p_Md82b

{
  "name": "teste_product",
  "description": "teste",
  "username_manufacturer": "danicarias"
}

##### EditProduct
PUT http://localhost:8080/embalagensinteligentes/api/products/3
Accept: application/json
Content-Type: application/json

{
  "name": "produto_alterado2",
  "description": "alterado",
  "username_manufacturer": "danicarias",
  "package_id": 1
}

##### DeleteProduct
DELETE http://localhost:8080/embalagensinteligentes/api/products/3
Accept: application/json

##### AddPackage
POST http://localhost:8080/embalagensinteligentes/api/products/4/package
Accept: application/json
Content-Type: application/json

{
    "id": 3
}

##### RemovePackage
DELETE http://localhost:8080/embalagensinteligentes/api/products/4/package
Accept: application/json


//--------------------PACKAGES
##### AllPackages
GET http://localhost:8080/embalagensinteligentes/api/packages
Accept: application/json

##### GetPackage
GET http://localhost:8080/embalagensinteligentes/api/packages/1
Accept: application/json

##### CreatePackage
POST http://localhost:8080/embalagensinteligentes/api/packages
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJkYW5pY2FyaWFzIiwiaWF0IjoxNzA1NjIyNDkwLCJleHAiOjE3MDU2MjI2MTB9.5skuVmOmtYHfcWAluRdJAOLbBBRdz-UQibewK9kiBB13WE11lskahM9k57nHWE6H

{
  "packageType": "PRIMARIA",
  "lastTimeOpened": "2022-01-01T12:30:00",
  "material": "PLASTICO2"
}

##### EditPackage
PUT http://localhost:8080/embalagensinteligentes/api/packages/3
Accept: application/json
Content-Type: application/json

{
  "packageType": 1,
  "lastTimeOpened": "2023-01-01T12:30:00",
  "material": "Pedra",
  "product_id": 2,
  "order_id": 1
}

##### DeletePackage
DELETE http://localhost:8080/embalagensinteligentes/api/packages/2
Accept: application/json

##### AddOrder
POST http://localhost:8080/embalagensinteligentes/api/packages/2/order
Accept: application/json
Content-Type: application/json

{
    "id": 1
}

##### RemoveOrder
DELETE http://localhost:8080/embalagensinteligentes/api/packages/2/order
Accept: application/json


//--------------------ORDERS
##### AllOrders
GET http://localhost:8080/embalagensinteligentes/api/orders
Accept: application/json

##### GetOrder
GET http://localhost:8080/embalagensinteligentes/api/orders/1
Accept: application/json

##### CreateOrder
POST http://localhost:8080/embalagensinteligentes/api/orders
Accept: application/json
Content-Type: application/json

{
  "endConsumer_username": "danicarias_outro"
}

##### EditOrder
PUT http://localhost:8080/embalagensinteligentes/api/orders/1
Accept: application/json
Content-Type: application/json

{
    "endConsumer_username": "danicarias_outro2"
}

##### DeleteOrder
DELETE http://localhost:8080/embalagensinteligentes/api/orders/1
Accept: application/json

##### GetPackages
GET http://localhost:8080/embalagensinteligentes/api/orders/1/packages
Accept: application/json


//--------------------SENSORS
##### AllSensors
GET http://localhost:8080/embalagensinteligentes/api/sensors
Accept: application/json

##### GetSensor
GET http://localhost:8080/embalagensinteligentes/api/sensors/1
Accept: application/json

##### CreateSensor
POST http://localhost:8080/embalagensinteligentes/api/sensors
Accept: application/json
Content-Type: application/json

{
  "name": "sensor_novo",
  "package_id": 1
}

##### EditSensor
PUT http://localhost:8080/embalagensinteligentes/api/sensors/1
Accept: application/json
Content-Type: application/json

{
  "name": "sensor_alterado",
  "package_id": 1
}

##### DeleteSensor
DELETE http://localhost:8080/embalagensinteligentes/api/sensors/1
Accept: application/json







####################################### NOVAS ROTAS #######################################







//--------------------LOGIN
##### Login
POST http://localhost:8080/embalagensinteligentes/api/auth/login
Accept: application/json
Content-Type: application/json

{
    "username": "danicarias",
    "password": "pass123"
}




##### GetEndConsumers
GET http://localhost:8080/embalagensinteligentes/api/endconsumers
Accept: application/json

##### GetEndConsumer
GET http://localhost:8080/embalagensinteligentes/api/endconsumers/danicarias_outro
Accept: application/json

##### CreateEndConsumer
POST http://localhost:8080/embalagensinteligentes/api/endconsumers
Accept: application/json
Content-Type: application/json

{
  "username": "danicarias_123",
  "name": "Daniel Carias",
  "password": "Daniel Carias",
  "address": "Rua 1",
  "phoneNumber": 123456789
}

##### EditEndConsumer
PUT http://localhost:8080/embalagensinteligentes/api/endconsumers/danicarias_123
Accept: application/json
Content-Type: application/json

{
  "name": "Daniel Carias",
  "address": "Rua 2",
  "phoneNumber": 111111111
}

##### DeleteEndConsumer
DELETE http://localhost:8080/embalagensinteligentes/api/endconsumers/danicarias_123
Accept: application/json

##### GetOrders
GET http://localhost:8080/embalagensinteligentes/api/endconsumers/danicarias_outro/orders
Accept: application/json




###########LogisticOperator ->>>>>> PASTA LOGISTIC OPERATOR
##### GetLogisticOperators
GET http://localhost:8080/embalagensinteligentes/api/logisticoperators
Accept: application/json

##### GetSensorsByPackage -> Adicionar na pasta dos Packages do bruno
GET http://localhost:8080/embalagensinteligentes/api/packages/2/sensors
Accept: application/json

##### GetLogisticOperator
GET http://localhost:8080/embalagensinteligentes/api/logisticoperators/danicarias_teste
Accept: application/json

##### CreateLogisticOperator
POST http://localhost:8080/embalagensinteligentes/api/logisticoperators
Accept: application/json
Content-Type: application/json

{
  "username": "novo_logisticoperator",
  "name": "Carlos Tojal",
  "password": "pass123",
  "address": "Rua BBR",
  "phoneNumber": 123456789
}

##### EditLogisticOperator
PUT http://localhost:8080/embalagensinteligentes/api/logisticoperators/novo_logisticoperator
Accept: application/json
Content-Type: application/json

{
  "name": "Carlos Tojal NOVO",
  "address": "Rua BBR  NOVO",
  "phoneNumber": 123456789
}

##### DeleteLogisticOperator
DELETE http://localhost:8080/embalagensinteligentes/api/logisticoperators/novo_logisticoperator
Accept: application/json


##### GetProductsByProductmanufactorer -> Adicionar na pasta dos Products do bruno
GET http://localhost:8080/embalagensinteligentes/api/products/manufacturer/pedro_dev
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJkYW5pY2FyaWFzIiwiaWF0IjoxNzA1NjA1MDE5LCJleHAiOjE3MDU2MDg2MTl9.m2UaIz8SMS5ZnIZBu0W5lCoPSNmi_xVSFBATMT2DA6sAA9-wIgAXCh8SZSnnLD9_



##### ProductManufacturer -> Adicionar na pasta dos ProductManufacturer do bruno
##### GetProductManufacturers
GET http://localhost:8080/embalagensinteligentes/api/productmanufacturers
Accept: application/json

##### GetProductManufacturer
GET http://localhost:8080/embalagensinteligentes/api/productmanufacturers/pedro_dev
Accept: application/json

##### CreateProductManufacturer
POST http://localhost:8080/embalagensinteligentes/api/productmanufacturers
Accept: application/json
Content-Type: application/json

{
    "username": "novo_productmanufacturer",
    "name": "Pedro Dev",
    "password": "pass123",
    "address": "Rua BBR",
    "phoneNumber": 123456789
}

##### EditProductManufacturer
PUT http://localhost:8080/embalagensinteligentes/api/productmanufacturers/novo_productmanufacturer
Accept: application/json
Content-Type: application/json

{
    "name": "Pedro Dev NOVO",
    "address": "Rua BBR NOVO",
    "phoneNumber": 123456789
}

##### DeleteProductManufacturer
DELETE http://localhost:8080/embalagensinteligentes/api/productmanufacturers/novo_productmanufacturer
Accept: application/json



################################################ NOVAS ROTAS ################################################33



##### GetPackagesByProductManufactorer -> Adicionar na pasta dos Packages do bruno
GET http://localhost:8080/embalagensinteligentes/api/packages/manufacturer/danicarias
Accept: application/json


##### GetOrdersByEndConsumer -> Adicionar na pasta dos Order do bruno
GET http://localhost:8080/embalagensinteligentes/api/orders/endconsumer/danicarias_outro
Accept: application/json



######################################## NOVASSSSSSS ROTAASSSSSSS ##########################################
####getAllProductsFromManufacturer
GET http://localhost:8080/embalagensinteligentes/api/products/manufacturer/pedro_dev
Accept: application/json

####getSensorsByPackage
GET http://localhost:8080/embalagensinteligentes/api/packages/1/sensors
Accept: application/json

