//--------------------PRODUCTS

##### AllProducts
GET http://localhost:8080/embalagensinteligentes/api/products
Accept: application/json

##### GetProduct
GET http://localhost:8080/embalagensinteligentes/api/products/2
Accept: application/json

##### CreateProduct
POST http://localhost:8080/embalagensinteligentes/api/products
Accept: application/json
Content-Type: application/json

{
  "name": "teste_product",
  "description": "teste",
  "username_manufacturer": "danicarias",
  "package_id": 0
}

##### EditProduct
PUT http://localhost:8080/embalagensinteligentes/api/products/4
Accept: application/json
Content-Type: application/json

{
  "name": "produto_alterado2",
  "description": "alterado",
  "username_manufacturer": "danicarias",
  "package_id": 1
}

##### DeleteProduct
DELETE http://localhost:8080/embalagensinteligentes/api/products/3
Accept: application/json

##### AddPackage
POST http://localhost:8080/embalagensinteligentes/api/products/1/addpackage
Accept: application/json
Content-Type: application/json

1

##### RemovePackage
POST http://localhost:8080/embalagensinteligentes/api/products/1/removepackage
Accept: application/json


//--------------------PACKAGES
##### AllPackages
GET http://localhost:8080/embalagensinteligentes/api/packages
Accept: application/json

##### GetPackage
GET http://localhost:8080/embalagensinteligentes/api/packages/1
Accept: application/json

##### CreatePackage
POST http://localhost:8080/embalagensinteligentes/api/packages
Accept: application/json
Content-Type: application/json

{
  "package_type": "PRIMARIA",
  "lastTimeOpened": "2022-01-01T12:30:00",
  "material": "PLASTICO2",
  "product_id": 1,
  "order_id": 1
}

##### EditPackage
PUT http://localhost:8080/embalagensinteligentes/api/packages/3
Accept: application/json
Content-Type: application/json

{
  "package_type": 1,
  "lastTimeOpened": "2023-01-01T12:30:00",
  "material": "Pedra",
  "product_id": 2,
  "order_id": 1
}

##### DeletePackage
DELETE http://localhost:8080/embalagensinteligentes/api/packages/1
Accept: application/json

##### AddOrder
POST http://localhost:8080/embalagensinteligentes/api/packages/1/addorder
Accept: application/json

1

##### RemoveOrder
POST http://localhost:8080/embalagensinteligentes/api/packages/1/removeorder
Accept: application/json












