//--------------------PRODUCTS

##### AllProducts
GET http://localhost:8080/embalagensinteligentes/api/products
Accept: application/json

##### GetProduct
GET http://localhost:8080/embalagensinteligentes/api/products/3
Accept: application/json

##### CreateProduct
POST http://localhost:8080/embalagensinteligentes/api/products
Accept: application/json
Content-Type: application/json

{
  "name": "teste_product",
  "description": "teste",
  "username_manufacturer": "danicarias",
  "package_id": 0
}

##### EditProduct
PUT http://localhost:8080/embalagensinteligentes/api/products/4
Accept: application/json
Content-Type: application/json

{
  "name": "produto_alterado2",
  "description": "alterado",
  "username_manufacturer": "danicarias",
  "package_id": 1
}

##### DeleteProduct
DELETE http://localhost:8080/embalagensinteligentes/api/products/3
Accept: application/json

##### AddPackage
POST http://localhost:8080/embalagensinteligentes/api/products/1/package
Accept: application/json
Content-Type: application/json

{
    "id": 2
}

##### RemovePackage
DELETE http://localhost:8080/embalagensinteligentes/api/products/1/package
Accept: application/json


//--------------------PACKAGES
##### AllPackages
GET http://localhost:8080/embalagensinteligentes/api/packages
Accept: application/json

##### GetPackage
GET http://localhost:8080/embalagensinteligentes/api/packages/1
Accept: application/json

##### CreatePackage
POST http://localhost:8080/embalagensinteligentes/api/packages
Accept: application/json
Content-Type: application/json

{
  "package_type": "PRIMARIA",
  "lastTimeOpened": "2022-01-01T12:30:00",
  "material": "PLASTICO2",
  "product_id": 1,
  "order_id": 1
}

##### EditPackage
PUT http://localhost:8080/embalagensinteligentes/api/packages/3
Accept: application/json
Content-Type: application/json

{
  "package_type": 1,
  "lastTimeOpened": "2023-01-01T12:30:00",
  "material": "Pedra",
  "product_id": 2,
  "order_id": 1
}

##### DeletePackage
DELETE http://localhost:8080/embalagensinteligentes/api/packages/1
Accept: application/json

##### AddOrder
POST http://localhost:8080/embalagensinteligentes/api/packages/2/order
Accept: application/json
Content-Type: application/json

{
    "id": 1
}

##### RemoveOrder
DELETE http://localhost:8080/embalagensinteligentes/api/packages/1/order
Accept: application/json


//--------------------ORDERS
##### AllOrders
GET http://localhost:8080/embalagensinteligentes/api/orders
Accept: application/json

##### GetOrder
GET http://localhost:8080/embalagensinteligentes/api/orders/1
Accept: application/json

##### CreateOrder
POST http://localhost:8080/embalagensinteligentes/api/orders
Accept: application/json
Content-Type: application/json

{
  "endConsumer_username": "danicarias_outro"
}

##### EditOrder
PUT http://localhost:8080/embalagensinteligentes/api/orders/1
Accept: application/json
Content-Type: application/json

{
    "endConsumer_username": "danicarias_outro2"
}

##### DeleteOrder
DELETE http://localhost:8080/embalagensinteligentes/api/orders/1
Accept: application/json

##### GetPackages
GET http://localhost:8080/embalagensinteligentes/api/orders/1/packages
Accept: application/json


//--------------------SENSORS
##### AllSensors
GET http://localhost:8080/embalagensinteligentes/api/sensors
Accept: application/json

##### GetSensor
GET http://localhost:8080/embalagensinteligentes/api/sensors/1
Accept: application/json

##### CreateSensor
POST http://localhost:8080/embalagensinteligentes/api/sensors
Accept: application/json
Content-Type: application/json

{
  "name": "sensor_novo",
  "package_id": 1
}

##### EditSensor
PUT http://localhost:8080/embalagensinteligentes/api/sensors/1
Accept: application/json
Content-Type: application/json

{
  "name": "sensor_alterado",
  "package_id": 1
}

##### DeleteSensor
DELETE http://localhost:8080/embalagensinteligentes/api/sensors/1
Accept: application/json








